### ISSUE TITLE
AssertionError: Frame too large!

### ISSUE THREAD

**Issue by bing0say** [qgy18/pangolin#9]
服务端启动成功，客户端启动成功，但是只要启动本地的服务，并访问服务器的域名，客户端就会报错，报错如下：
`
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Frame too large!
    at Serializer._transform (/usr/local/lib/node_modules/pangolin/lib/node-http2/lib/protocol/framer.js:46:3)
    at Serializer.Transform._read (_stream_transform.js:167:10)
    at Serializer.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
    at Serializer.Writable.write (_stream_writable.js:246:11)
    at Compressor.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Compressor.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
`
node 的版本为v6.9.1 ，macOS 的版本为 10.12.1 ，折腾了几天，不知道问题是系统的原因，还是 node 的原因。
在 linux 端可正常运行，还望指教，谢谢。

**Comment by bing0say** [comment]
弄好了，来反馈下。node 版本改为了 v5.12.0，可以成功运行。

**Comment by qgy18** [comment]
抽空修了一下，测试了 v6.9.1，应该也可以了。

**Comment by bing0say** [comment]
了解，感谢。
